### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by jhonoryza** [eleftrik/laradhoc#1]
how to choose php version?, i have an existing laravel project with php 7.2

**Comment by eleftrik** [comment]
> how to choose php version?, i have an existing laravel project with php 7.2

Hi @jhonoryza, thanks for your request.
I'll release this feature as soon as possible.
Stay tuned!

**Comment by eleftrik** [comment]
@jhonoryza With release 1.5.0 now you're able to specify which version of PHP to run.

In your case, just set `PHP_VERSION=7.2` in your `.env` file.

Remember to rebuild by running `.docker/scripts/init`.

Let me know if everything works as expected.
Thank you

Closed via https://github.com/eleftrik/laradhoc/commit/33b5eabef3bd84b2a81a4e45c37d359e13327363
