### ISSUE TITLE
Not working ssl 

### ISSUE THREAD

**Issue by developcreativo** [eleftrik/laradhoc#11]
![Captura de pantalla_área-de-selección_20220929114657](https://user-images.githubusercontent.com/5873347/193078171-0b2c66e2-4fcf-4d30-a754-0112eac7cda7.jpg)

# Set to 1 to enable HTTPS, 0 to run only over HTTP
NGINX_ENABLE_HTTPS=1

![Captura de pantalla_área-de-selección_20220929121449](https://user-images.githubusercontent.com/5873347/193084161-c062e536-682e-443b-a616-aedd50b022de.jpg)

![Captura de pantalla_área-de-selección_20220929122248](https://user-images.githubusercontent.com/5873347/193086009-fb71ddfb-55f5-4187-8891-a27cd5b54585.jpg)

**Comment by eleftrik** [comment]
Hi @developcreativo and sorry for the long delay.
I've just setup a new project with `NGINX_ENABLE_HTTPS=1` and I can't reproduce your issue.
I got HTTPS working (with a dummy index.php):

<img width="444" alt="image" src="https://user-images.githubusercontent.com/6959298/195872507-946ab4f0-8f1d-490f-9dd7-2eb0eeefd2bc.png">

- which version of laradhoc are you using?
- which files do you have under `<project>.docker/images/nginx/ssl`?

I think you should see
- `fikrea.test.crt`
- `fikrea.test.key`

In my example, I got
- `laradhoc.test.crt`
- `laradhoc.test.key`

which are then mounted in the nginx container:

```shell
❯ docker exec -it laradhoc_nginx /bin/bash
root@32ec4d01ee46:/var/www# cd /etc/ssl/certs/
root@32ec4d01ee46:/etc/ssl/certs# ls -la
total 20
drwxr-xr-x 2 root root 4096 Oct 14 14:15 .
drwxr-xr-x 1 root root 4096 Oct 14 14:15 ..
-rw-r--r-- 1 root root   86 Oct 14 14:13 .gitignore
-rw-r--r-- 1 root root    0 Oct 14 14:13 .gitkeep
-rw-r--r-- 1 root root 1818 Oct 14 14:15 laradhoc.test.crt
-rw-r--r-- 1 root root 3272 Oct 14 14:15 laradhoc.test.key
root@32ec4d01ee46:/etc/ssl/certs#
```

Did you also try to rebuild the containers?
