### ISSUE TITLE
Upgrade to PHP_VERSION=8.2

### ISSUE THREAD

**Issue by xnekv03** [eleftrik/laradhoc#12]
Hello,
would it be possible to upgrade to PHP_VERSION=8.2 ?

Thank you in advance

**Comment by eleftrik** [comment]
> Hello, would it be possible to upgrade to PHP_VERSION=8.2 ?
> 
> Thank you in advance

Versione 2.4.0 released: https://github.com/eleftrik/laradhoc/releases/tag/2.4.0

Anyway, I suggest to move to Laravel Sail (if you need to use Docker) or - a better option, in my opinion - Valet.

Enjoy!

**Comment by xnekv03** [comment]
Thank you - great package.
I have problems with sail on my Windows environments, that's why I stick with your package.

**Comment by encodiaweb** [comment]
> Thank you - great package. I have problems with sail on my Windows environments, that's why I stick with your package.

Happy to help! 😁
