### ISSUE TITLE
echosystem of larvel is not much wast

### ISSUE THREAD

**Issue by madilraza** [eleftrik/laradhoc#3]
Laravel is a PHP MVC framework and Node JS is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node JS is leading in the entire web and Laravel is still behind Node JS in all market share segments

**Comment by eleftrik** [comment]
Exactly, what's the purpose of your issue?
This is NOT a forum where people can argue about what's their preferred technology.
If you don't like Laravel or its ecosystem, don't use it. But please don't bother who is interested in.
