### ISSUE TITLE
failed to open stream

### ISSUE THREAD

**Issue by bolloplayer** [eleftrik/laradhoc#5]
Hello , 
 running under W10 with  wsl2, debian  and Docker Desktop.
I can create the containers with `.docker/scripts/init`. No errors here and i see the containers in Docker Desktop. 

When I run `./.docker/scripts/install-laravel` to test, I get an error 
`File ./src/.env found. Performing variable replacing...
.docker/scripts/init-laravel: line 45: ./src/.env: Permission denied`

I can run this command as sudo,  but then i get errors like `file_put_contents(/var/www/storage/framework/sessions/wh..5e6p8AqD): failed to open stream: Permission denied`

Any thoughts? 

Marcus Winckers

**Comment by eleftrik** [comment]
Hi @bolloplayer, I think sudo shouldn't be used in this case.

After the error, who's the owner of `./src/.env`?
What user are you running this scripts under?

**Comment by bolloplayer** [comment]
After i run   init, , i have an empty scr/   directory .
The chmod is:
drwxr-xr-x 2 marcus marcus 4096 May  4 20:39 src
Running under my user  : marcus .


 then i have run  ./.docker/scripts/install-laravel   and after installing
the laravel project  i get the  error:

*File ./src/.env found. Performing variable
replacing....docker/scripts/init-laravel: line 45: ./src/.env: Permission
denied*

\In the  /src directory  i see an .env  file, but this is the default .env
file without my  personal settings
DB_DATABASE=laravel
DB_USERNAME=root
The ./src/.env file: is root root  * << Is that correct, how can the ./src
direct be root i f i run it  with the bash command install-laravel?  *

marcus@DESKTOP-DPSNON3:~/laradhoc.test/src$ ls -la
total 308
drwxr-xr-x 12 marcus marcus   4096 May  4 21:29 .
drwxr-xr-x  5 marcus marcus   4096 May  4 21:27 ..
drwxr-xr-x  6 root   root     4096 Apr 15 13:46 app
-rwxr-xr-x  1 root   root     1686 Apr 15 13:46 artisan
drwxr-xr-x  3 root   root     4096 Apr 15 13:46 bootstrap
-rw-r--r--  1 root   root     1586 Apr 15 13:46 composer.json
-rw-r--r--  1 root   root   207572 May  4 21:29 composer.lock
drwxr-xr-x  2 root   root     4096 Apr 15 13:46 config
drwxr-xr-x  5 root   root     4096 Apr 15 13:46 database
-rw-r--r--  1 root   root      220 Apr 15 13:46 .editorconfig
-rw-r--r--  1 root   root      829 May  4 21:29 .env
-rw-r--r--  1 root   root      778 Apr 15 13:46 .env.example
-rw-r--r--  1 root   root      111 Apr 15 13:46 .gitattributes
-rw-r--r--  1 root   root      163 Apr 15 13:46 .gitignore
-rw-r--r--  1 root   root     1013 Apr 15 13:46 package.json
-rw-r--r--  1 root   root     1197 Apr 15 13:46 phpunit.xml
drwxr-xr-x  2 root   root     4096 Apr 15 13:46 public
-rw-r--r--  1 root   root     4497 Apr 15 13:46 README.md
drwxr-xr-x  6 root   root     4096 Apr 15 13:46 resources
drwxr-xr-x  2 root   root     4096 Apr 15 13:46 routes
-rw-r--r--  1 root   root      563 Apr 15 13:46 server.php
drwxr-xr-x  5 root   root     4096 Apr 15 13:46 storage
-rw-r--r--  1 root   root      174 Apr 15 13:46 .styleci.yml
drwxr-xr-x  4 root   root     4096 Apr 15 13:46 tests
drwxr-xr-x 44 root   root     4096 May  4 21:29 vendor
-rw-r--r--  1 root   root      538 Apr 15 13:46 webpack.mix.js

 m arcus


-








Op ma 4 mei 2020 om 16:37 schreef eleftrik <notifications@github.com>:

**Comment by bolloplayer** [comment]
Hello Eric,

after the install-laravel command, the directory ./src  has root root
privs.
Because of docker-compose run .
The .env file is then not written, because that has user user privs.

I did a  chown on src/
sudo chown marcus:marcus src/ -R

And then to get the correct .env file:
init-laravel

That gives me the  Hello Laravel website !!!

I think it is no problem on a Mac, only on Linux?

PErhaps you can give in the .env file  something like UID=1000
and then use the $UID  in the install-laravel?

marcus



Op ma 4 mei 2020 om 21:38 schreef Marcus Winckers <marckie61@gmail.com>:

**Comment by eleftrik** [comment]
Sorry @bolloplayer, but I'm not able to reproduce your issue.

> after the install-laravel command, the directory ./src  has root root
privs.

Are you running any script as root?
I'm not using `sudo` in the scripts. I can't understand how your `.env` file can be owned by root; same for your `src/` folder.

Can you please post the content of your .env file and, if possible, the exact sequence of the commands your issuing along with the output?

**Comment by eleftrik** [comment]
@bolloplayer Any news?
