### ISSUE TITLE
Help getting php7.4-gd to work

### ISSUE THREAD

**Issue by nateajohnson** [eleftrik/laradhoc#6]
Anyone know how to get php7.4-gd working inside of docker?

I tried this inside of the php-fpm Dockerfile but got errors.

```
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    rm -rf /var/lib/apt/lists/*
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update && apt-get install -y --no-install-recommends php7.4-gd
```

E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu groovy Release' does not have a Release file.

**Comment by eleftrik** [comment]
> Anyone know how to get php7.4-gd working inside of docker?

Hi @nateajohnson, are you having troubles with GD in Laradhoc's php-fpm container? Or are you talking about getting php7.4-gd working in general?
