### ISSUE TITLE
ldap extension

### ISSUE THREAD

**Issue by xnekv03** [eleftrik/laradhoc#7]
Would it be possible to add ldap extension to Dockerfile in php-fpm image?

Thank you

**Comment by eleftrik** [comment]
> Would it be possible to add ldap extension to Dockerfile in php-fpm image?
> 
> Thank you

Hi @xnekv03, yes, of course.
I will add it as soon as possible!

**Comment by eleftrik** [comment]
Version [1.7.0](https://github.com/eleftrik/laradhoc/releases/tag/1.7.0) has been released.
After updating, remember to rebuild images: `.docker/scripts/start --build`.
Please let me know in case you're facing any issue.

**Comment by xnekv03** [comment]
Thank you sir! Works perfectly

**Comment by eleftrik** [comment]
@xnekv03 Thanks for your suggestion. You're welcome :-)
