### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by xnekv03** [eleftrik/laradhoc#8]
Hello and thank you for great package. Would it be possible to add MongoDB as an option to that package?

Thank you

**Comment by eleftrik** [comment]
Hi @xnekv03, thanks. Great suggestion! Personally, I have to admit I never used MongoDB. But I think a dedicated container could be easily added.
I'll try as soon as possible.
Any request about a particular configuration for Laravel?

**Comment by xnekv03** [comment]
The trick is to install all the php extensions and enable them properly - quite a struggle for me personally.
I can test it for you if you want that it works.
Thanks

**Comment by eleftrik** [comment]
Hi @xnekv03, sorry for the delay.
Just released version `1.8.0`.

Please note I didn't and I don't have a MongoDB background at all, so I could have missed something basic 😅 I didn't try to connect from Laravel to MongoDB; just checked the connection to the service.
In case you're upgrading an existing project, take a look at `.env.example` to add the new `MONGODB_*` variables to your `.env` file, then rebuild containers.

Please let me know if you encounter any issues or you have any suggestions! Thank you

**Comment by xnekv03** [comment]
Hello,
thanks for the change but unfortunately I was unable to connect to Mongo with Laravel.
I forked your repository and modified
 
added some mongo specific environment variables
- https://github.com/xnekv03/laradhoc/blob/master/src/.env

added mogo connection config
- https://github.com/xnekv03/laradhoc/blob/master/src/config/database.php

Unfortunately there is still one docker problem that mongo drivers are missing. 
Steps to reproduce. 

- `git clone git@github.com:xnekv03/laradhoc.git`
- spin up docker containers
- run `php artisan migrate:fresh`
-  you will get an error `Unsupported driver [mongodb].` 

Thank you in advance


![error](https://i.imgur.com/cbczP9Z.png)
